const periodicTableData = [
  {
    name: 'Hydrogen',
    atomicNumber: 1,
    symbol: 'H',
    category: 'Reactive nonmetal',
    atomicWeight: '1.008',
    atomicWeightFull: '[1.00784, 1.00811]',
    occurrence: 'gas',
    stateOfMatter: 'primordial',
    group: 1,
    period: 1,
    block: 's',
    tablerowcol: 1,
    tablecolumncol: 1,
    visible: true,
  },
  {
    name: 'Helium',
    atomicNumber: 2,
    symbol: 'He',
    category: 'noble gas',
    atomicWeight: '4.0026',
    atomicWeightFull: '4.002602(2)',
    occurrence: 'gas',
    stateOfMatter: 'primordial',
    group: 18,
    period: 1,
    block: 's',
    tablerowcol: 1,
    tablecolumncol: 18,
    visible: true,
  },
  {
    name: 'Lithium',
    atomicNumber: 3,
    symbol: 'Li',
    category: 'Alkali metal',
    atomicWeight: '6.94',
    atomicWeightFull: '[6.938, 6.997]',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 1,
    period: 2,
    block: 's',
    tablerowcol: 2,
    tablecolumncol: 1,
    visible: true,
  },
  {
    name: 'Beryllium',
    atomicNumber: 4,
    symbol: 'Be',
    category: 'alkaline earth metal',
    atomicWeight: '9.0122',
    atomicWeightFull: '9.0121831(5)',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 2,
    period: 2,
    block: 's',
    tablerowcol: 2,
    tablecolumncol: 2,
    visible: true,
  },
  {
    name: 'Boron',
    atomicNumber: 5,
    symbol: 'B',
    category: 'metalloid',
    atomicWeight: '10.81',
    atomicWeightFull: '[10.806, 10.821]',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 13,
    period: 2,
    block: 'p',
    tablerowcol: 2,
    tablecolumncol: 13,
    visible: true,
  },
  {
    name: 'Carbon',
    atomicNumber: 6,
    symbol: 'C',
    category: 'Reactive nonmetal',
    atomicWeight: '12.011',
    atomicWeightFull: '[12.0096, 12.0116]',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 14,
    period: 2,
    block: 'p',
    tablerowcol: 2,
    tablecolumncol: 14,
    visible: true,
  },
  {
    name: 'Nitrogen',
    atomicNumber: 7,
    symbol: 'N',
    category: 'Reactive nonmetal',
    atomicWeight: '14.007',
    atomicWeightFull: '[14.00643, 14.00728]',
    occurrence: 'gas',
    stateOfMatter: 'primordial',
    group: 15,
    period: 2,
    block: 'p',
    tablerowcol: 2,
    tablecolumncol: 15,
    visible: true,
  },
  {
    name: 'Oxygen',
    atomicNumber: 8,
    symbol: 'O',
    category: 'Reactive nonmetal',
    atomicWeight: '15.999',
    atomicWeightFull: '[15.99903, 15.99977]',
    occurrence: 'gas',
    stateOfMatter: 'primordial',
    group: 16,
    period: 2,
    block: 'p',
    tablerowcol: 2,
    tablecolumncol: 16,
    visible: true,
  },
  {
    name: 'Fluorine',
    atomicNumber: 9,
    symbol: 'F',
    category: 'Reactive nonmetal',
    atomicWeight: '18.998',
    atomicWeightFull: '18.998403163(6)',
    occurrence: 'gas',
    stateOfMatter: 'primordial',
    group: 17,
    period: 2,
    block: 'p',
    tablerowcol: 2,
    tablecolumncol: 17,
    visible: true,
  },
  {
    name: 'Neon',
    atomicNumber: 10,
    symbol: 'Ne',
    category: 'noble gas',
    atomicWeight: '20.18',
    atomicWeightFull: '20.1797(6)',
    occurrence: 'gas',
    stateOfMatter: 'primordial',
    group: 18,
    period: 2,
    block: 'p',
    tablerowcol: 2,
    tablecolumncol: 18,
    visible: true,
  },
  {
    name: 'Sodium',
    atomicNumber: 11,
    symbol: 'Na',
    category: 'Alkali metal',
    atomicWeight: '22.99',
    atomicWeightFull: '22.98976928(2) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 1,
    period: 3,
    block: 's',
    tablerowcol: 3,
    tablecolumncol: 1,
    visible: true,
  },
  {
    name: 'Magnesium',
    atomicNumber: 12,
    symbol: 'Mg',
    category: 'alkaline earth metal',
    atomicWeight: '24.305',
    atomicWeightFull: '[24.304, 24.307] ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 2,
    period: 3,
    block: 's',
    tablerowcol: 3,
    tablecolumncol: 2,
    visible: true,
  },
  {
    name: 'Aluminium',
    atomicNumber: 13,
    symbol: 'Al',
    category: 'post-transition metal',
    atomicWeight: '26.982',
    atomicWeightFull: '26.9815384(3) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 13,
    period: 3,
    block: 'p',
    tablerowcol: 3,
    tablecolumncol: 13,
    visible: true,
  },
  {
    name: 'Silicon',
    atomicNumber: 14,
    symbol: 'Si',
    category: 'metalloid',
    atomicWeight: '28.085',
    atomicWeightFull: '[28.084, 28.086] ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 14,
    period: 3,
    block: 'p',
    tablerowcol: 3,
    tablecolumncol: 14,
    visible: true,
  },
  {
    name: 'Phosphorus',
    atomicNumber: 15,
    symbol: 'P',
    category: 'Reactive nonmetal',
    atomicWeight: '30.974',
    atomicWeightFull: '30.973761998(5) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 15,
    period: 3,
    block: 'p',
    tablerowcol: 3,
    tablecolumncol: 15,
    visible: true,
  },
  {
    name: 'Sulfur',
    atomicNumber: 16,
    symbol: 'S',
    category: 'Reactive nonmetal',
    atomicWeight: '32.06',
    atomicWeightFull: '[32.059, 32.076] ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 16,
    period: 3,
    block: 'p',
    tablerowcol: 3,
    tablecolumncol: 16,
    visible: true,
  },
  {
    name: 'Chlorine',
    atomicNumber: 17,
    symbol: 'Cl',
    category: 'Reactive nonmetal',
    atomicWeight: '35.45',
    atomicWeightFull: '[35.446, 35.457] ',
    occurrence: 'gas',
    stateOfMatter: 'primordial',
    group: 17,
    period: 3,
    block: 'p',
    tablerowcol: 3,
    tablecolumncol: 17,
    visible: true,
  },
  {
    name: 'Argon',
    atomicNumber: 18,
    symbol: 'Ar',
    category: 'noble gas',
    atomicWeight: '39.95',
    atomicWeightFull: '[39.792, 39.963] ',
    occurrence: 'gas',
    stateOfMatter: 'primordial',
    group: 18,
    period: 3,
    block: 'p',
    tablerowcol: 3,
    tablecolumncol: 18,
    visible: true,
  },
  {
    name: 'Potassium',
    atomicNumber: 19,
    symbol: 'K',
    category: 'Alkali metal',
    atomicWeight: '39.098',
    atomicWeightFull: '39.0983(1) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 1,
    period: 4,
    block: 's',
    tablerowcol: 4,
    tablecolumncol: 1,
    visible: true,
  },
  {
    name: 'Calcium',
    atomicNumber: 20,
    symbol: 'Ca',
    category: 'alkaline earth metal',
    atomicWeight: '40.078',
    atomicWeightFull: '40.078(4) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 2,
    period: 4,
    block: 's',
    tablerowcol: 4,
    tablecolumncol: 2,
    visible: true,
  },
  {
    name: 'Scandium',
    atomicNumber: 21,
    symbol: 'Sc',
    category: 'transition metal',
    atomicWeight: '44.956',
    atomicWeightFull: '44.955908(5) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 3,
    period: 4,
    block: 'd',
    tablerowcol: 4,
    tablecolumncol: 3,
    visible: true,
  },
  {
    name: 'Titanium',
    atomicNumber: 22,
    symbol: 'Ti',
    category: 'transition metal',
    atomicWeight: '47.867',
    atomicWeightFull: '47.867(1) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 4,
    period: 4,
    block: 'd',
    tablerowcol: 4,
    tablecolumncol: 4,
    visible: true,
  },
  {
    name: 'Vanadium',
    atomicNumber: 23,
    symbol: 'V',
    category: 'transition metal',
    atomicWeight: '50.942',
    atomicWeightFull: '50.9415(1) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 5,
    period: 4,
    block: 'd',
    tablerowcol: 4,
    tablecolumncol: 5,
    visible: true,
  },
  {
    name: 'Chromium',
    atomicNumber: 24,
    symbol: 'Cr',
    category: 'transition metal',
    atomicWeight: '51.996',
    atomicWeightFull: '51.9961(6) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 6,
    period: 4,
    block: 'd',
    tablerowcol: 4,
    tablecolumncol: 6,
    visible: true,
  },
  {
    name: 'Manganese',
    atomicNumber: 25,
    symbol: 'Mn',
    category: 'transition metal',
    atomicWeight: '54.938',
    atomicWeightFull: '54.938043(2) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 7,
    period: 4,
    block: 'd',
    tablerowcol: 4,
    tablecolumncol: 7,
    visible: true,
  },
  {
    name: 'Iron',
    atomicNumber: 26,
    symbol: 'Fe',
    category: 'transition metal',
    atomicWeight: '55.845',
    atomicWeightFull: '55.845(2) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 8,
    period: 4,
    block: 'd',
    tablerowcol: 4,
    tablecolumncol: 8,
    visible: true,
  },
  {
    name: 'Cobalt',
    atomicNumber: 27,
    symbol: 'Co',
    category: 'transition metal',
    atomicWeight: '58.933',
    atomicWeightFull: '58.933194(3) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 9,
    period: 4,
    block: 'd',
    tablerowcol: 4,
    tablecolumncol: 9,
    visible: true,
  },
  {
    name: 'Nickel',
    atomicNumber: 28,
    symbol: 'Ni',
    category: 'transition metal',
    atomicWeight: '58.693',
    atomicWeightFull: '58.6934(4) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 10,
    period: 4,
    block: 'd',
    tablerowcol: 4,
    tablecolumncol: 10,
    visible: true,
  },
  {
    name: 'Copper',
    atomicNumber: 29,
    symbol: 'Cu',
    category: 'transition metal',
    atomicWeight: '63.546',
    atomicWeightFull: '63.546(3) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 11,
    period: 4,
    block: 'd',
    tablerowcol: 4,
    tablecolumncol: 11,
    visible: true,
  },
  {
    name: 'Zinc',
    atomicNumber: 30,
    symbol: 'Zn',
    category: 'post-transition metal',
    atomicWeight: '65.38',
    atomicWeightFull: '65.38(2) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 12,
    period: 4,
    block: 'd',
    tablerowcol: 4,
    tablecolumncol: 12,
    visible: true,
  },
  {
    name: 'Gallium',
    atomicNumber: 31,
    symbol: 'Ga',
    category: 'post-transition metal',
    atomicWeight: '69.723',
    atomicWeightFull: '69.723(1) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 13,
    period: 4,
    block: 'p',
    tablerowcol: 4,
    tablecolumncol: 13,
    visible: true,
  },
  {
    name: 'Germanium',
    atomicNumber: 32,
    symbol: 'Ge',
    category: 'metalloid',
    atomicWeight: '72.63',
    atomicWeightFull: '72.630(8) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 14,
    period: 4,
    block: 'p',
    tablerowcol: 4,
    tablecolumncol: 14,
    visible: true,
  },
  {
    name: 'Arsenic',
    atomicNumber: 33,
    symbol: 'As',
    category: 'metalloid',
    atomicWeight: '74.922',
    atomicWeightFull: '74.921595(6) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 15,
    period: 4,
    block: 'p',
    tablerowcol: 4,
    tablecolumncol: 15,
    visible: true,
  },
  {
    name: 'Selenium',
    atomicNumber: 34,
    symbol: 'Se',
    category: 'Reactive nonmetal',
    atomicWeight: '78.971',
    atomicWeightFull: '78.971(8) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 16,
    period: 4,
    block: 'p',
    tablerowcol: 4,
    tablecolumncol: 16,
    visible: true,
  },
  {
    name: 'Bromine',
    atomicNumber: 35,
    symbol: 'Br',
    category: 'Reactive nonmetal',
    atomicWeight: '79.904',
    atomicWeightFull: '[79.901, 79.907] ',
    occurrence: 'Liquid',
    stateOfMatter: 'primordial',
    group: 17,
    period: 4,
    block: 'p',
    tablerowcol: 4,
    tablecolumncol: 17,
    visible: true,
  },
  {
    name: 'Krypton',
    atomicNumber: 36,
    symbol: 'Kr',
    category: 'noble gas',
    atomicWeight: '83.798',
    atomicWeightFull: '83.798(2) ',
    occurrence: 'gas',
    stateOfMatter: 'primordial',
    group: 18,
    period: 4,
    block: 'p',
    tablerowcol: 4,
    tablecolumncol: 18,
    visible: true,
  },
  {
    name: 'Rubidium',
    atomicNumber: 37,
    symbol: 'Rb',
    category: 'Alkali metal',
    atomicWeight: '85.468',
    atomicWeightFull: '85.4678(3) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 1,
    period: 5,
    block: 's',
    tablerowcol: 5,
    tablecolumncol: 1,
    visible: true,
  },
  {
    name: 'Strontium',
    atomicNumber: 38,
    symbol: 'Sr',
    category: 'alkaline earth metal',
    atomicWeight: '87.62',
    atomicWeightFull: '87.62(1) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 2,
    period: 5,
    block: 's',
    tablerowcol: 5,
    tablecolumncol: 2,
    visible: true,
  },
  {
    name: 'Yttrium',
    atomicNumber: 39,
    symbol: 'Y',
    category: 'transition metal',
    atomicWeight: '88.906',
    atomicWeightFull: '88.90584(1) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 3,
    period: 5,
    block: 'd',
    tablerowcol: 5,
    tablecolumncol: 3,
    visible: true,
  },
  {
    name: 'Zirconium',
    atomicNumber: 40,
    symbol: 'Zr',
    category: 'transition metal',
    atomicWeight: '91.224',
    atomicWeightFull: '91.224(2) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 4,
    period: 5,
    block: 'd',
    tablerowcol: 5,
    tablecolumncol: 4,
    visible: true,
  },
  {
    name: 'Niobium',
    atomicNumber: 41,
    symbol: 'Nb',
    category: 'transition metal',
    atomicWeight: '92.906',
    atomicWeightFull: '92.90637(1) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 5,
    period: 5,
    block: 'd',
    tablerowcol: 5,
    tablecolumncol: 5,
    visible: true,
  },
  {
    name: 'Molybdenum',
    atomicNumber: 42,
    symbol: 'Mo',
    category: 'transition metal',
    atomicWeight: '95.95',
    atomicWeightFull: '95.95(1) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 6,
    period: 5,
    block: 'd',
    tablerowcol: 5,
    tablecolumncol: 6,
    visible: true,
  },
  {
    name: 'Technetium',
    atomicNumber: 43,
    symbol: 'Tc',
    category: 'transition metal',
    atomicWeight: '[97]',
    atomicWeightFull: '-',
    occurrence: 'solid',
    stateOfMatter: 'from decay',
    group: 7,
    period: 5,
    block: 'd',
    tablerowcol: 5,
    tablecolumncol: 7,
    visible: true,
  },
  {
    name: 'Ruthenium',
    atomicNumber: 44,
    symbol: 'Ru',
    category: 'transition metal',
    atomicWeight: '101.07',
    atomicWeightFull: '101.07(2) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 8,
    period: 5,
    block: 'd',
    tablerowcol: 5,
    tablecolumncol: 8,
    visible: true,
  },
  {
    name: 'Rhodium',
    atomicNumber: 45,
    symbol: 'Rh',
    category: 'transition metal',
    atomicWeight: '102.91',
    atomicWeightFull: '102.90549(2) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 9,
    period: 5,
    block: 'd',
    tablerowcol: 5,
    tablecolumncol: 9,
    visible: true,
  },
  {
    name: 'Palladium',
    atomicNumber: 46,
    symbol: 'Pd',
    category: 'transition metal',
    atomicWeight: '106.42',
    atomicWeightFull: '106.42(1) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 10,
    period: 5,
    block: 'd',
    tablerowcol: 5,
    tablecolumncol: 10,
    visible: true,
  },
  {
    name: 'Silver',
    atomicNumber: 47,
    symbol: 'Ag',
    category: 'transition metal',
    atomicWeight: '107.87',
    atomicWeightFull: '107.8682(2) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 11,
    period: 5,
    block: 'd',
    tablerowcol: 5,
    tablecolumncol: 11,
    visible: true,
  },
  {
    name: 'Cadmium',
    atomicNumber: 48,
    symbol: 'Cd',
    category: 'post-transition metal',
    atomicWeight: '112.41',
    atomicWeightFull: '112.414(4) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 12,
    period: 5,
    block: 'd',
    tablerowcol: 5,
    tablecolumncol: 12,
    visible: true,
  },
  {
    name: 'Indium',
    atomicNumber: 49,
    symbol: 'In',
    category: 'post-transition metal',
    atomicWeight: '114.82',
    atomicWeightFull: '114.818(1) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 13,
    period: 5,
    block: 'p',
    tablerowcol: 5,
    tablecolumncol: 13,
    visible: true,
  },
  {
    name: 'Tin',
    atomicNumber: 50,
    symbol: 'Sn',
    category: 'post-transition metal',
    atomicWeight: '118.71',
    atomicWeightFull: '118.710(7) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 14,
    period: 5,
    block: 'p',
    tablerowcol: 5,
    tablecolumncol: 14,
    visible: true,
  },
  {
    name: 'Antimony',
    atomicNumber: 51,
    symbol: 'Sb',
    category: 'metalloid',
    atomicWeight: '121.76',
    atomicWeightFull: '121.760(1) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 15,
    period: 5,
    block: 'p',
    tablerowcol: 5,
    tablecolumncol: 15,
    visible: true,
  },
  {
    name: 'Tellurium',
    atomicNumber: 52,
    symbol: 'Te',
    category: 'metalloid',
    atomicWeight: '127.6',
    atomicWeightFull: '127.60(3) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 16,
    period: 5,
    block: 'p',
    tablerowcol: 5,
    tablecolumncol: 16,
    visible: true,
  },
  {
    name: 'Iodine',
    atomicNumber: 53,
    symbol: 'I',
    category: 'Reactive nonmetal',
    atomicWeight: '126.9',
    atomicWeightFull: '126.90447(3) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 17,
    period: 5,
    block: 'p',
    tablerowcol: 5,
    tablecolumncol: 17,
    visible: true,
  },
  {
    name: 'Xenon',
    atomicNumber: 54,
    symbol: 'Xe',
    category: 'noble gas',
    atomicWeight: '131.29',
    atomicWeightFull: '131.293(6) ',
    occurrence: 'gas',
    stateOfMatter: 'primordial',
    group: 18,
    period: 5,
    block: 'p',
    tablerowcol: 5,
    tablecolumncol: 18,
    visible: true,
  },
  {
    name: 'Caesium',
    atomicNumber: 55,
    symbol: 'Cs',
    category: 'Alkali metal',
    atomicWeight: '132.91',
    atomicWeightFull: '132.90545196(6) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 1,
    period: 6,
    block: 's',
    tablerowcol: 6,
    tablecolumncol: 1,
    visible: true,
  },
  {
    name: 'Barium',
    atomicNumber: 56,
    symbol: 'Ba',
    category: 'alkaline earth metal',
    atomicWeight: '137.33',
    atomicWeightFull: '137.327(7) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 2,
    period: 6,
    block: 's',
    tablerowcol: 6,
    tablecolumncol: 2,
    visible: true,
  },
  {
    name: 'Lanthanum',
    atomicNumber: 57,
    symbol: 'La',
    category: 'Lanthanide',
    atomicWeight: '138.91',
    atomicWeightFull: '138.90547(7) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 3,
    period: 6,
    block: 'd',
    tablerowcol: 8,
    tablecolumncol: 4,
    visible: true,
  },
  {
    name: 'Cerium',
    atomicNumber: 58,
    symbol: 'Ce',
    category: 'Lanthanide',
    atomicWeight: '140.12',
    atomicWeightFull: '140.116(1) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 0,
    period: 6,
    block: 'f',
    tablerowcol: 8,
    tablecolumncol: 5,
    visible: true,
  },
  {
    name: 'Praseodymium',
    atomicNumber: 59,
    symbol: 'Pr',
    category: 'Lanthanide',
    atomicWeight: '140.91',
    atomicWeightFull: '140.90766(1) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 0,
    period: 6,
    block: 'f',
    tablerowcol: 8,
    tablecolumncol: 6,
    visible: true,
  },
  {
    name: 'Neodymium',
    atomicNumber: 60,
    symbol: 'Nd',
    category: 'Lanthanide',
    atomicWeight: '144.24',
    atomicWeightFull: '144.242(3) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 0,
    period: 6,
    block: 'f',
    tablerowcol: 8,
    tablecolumncol: 7,
    visible: true,
  },
  {
    name: 'Promethium',
    atomicNumber: 61,
    symbol: 'Pm',
    category: 'Lanthanide',
    atomicWeight: '[145]',
    atomicWeightFull: '-',
    occurrence: 'solid',
    stateOfMatter: 'from decay',
    group: 0,
    period: 6,
    block: 'f',
    tablerowcol: 8,
    tablecolumncol: 8,
    visible: true,
  },
  {
    name: 'Samarium',
    atomicNumber: 62,
    symbol: 'Sm',
    category: 'Lanthanide',
    atomicWeight: '150.36',
    atomicWeightFull: '150.36(2) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 0,
    period: 6,
    block: 'f',
    tablerowcol: 8,
    tablecolumncol: 9,
    visible: true,
  },
  {
    name: 'Europium',
    atomicNumber: 63,
    symbol: 'Eu',
    category: 'Lanthanide',
    atomicWeight: '151.96',
    atomicWeightFull: '151.964(1) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 0,
    period: 6,
    block: 'f',
    tablerowcol: 8,
    tablecolumncol: 10,
    visible: true,
  },
  {
    name: 'Gadolinium',
    atomicNumber: 64,
    symbol: 'Gd',
    category: 'Lanthanide',
    atomicWeight: '157.25',
    atomicWeightFull: '157.25(3) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 0,
    period: 6,
    block: 'f',
    tablerowcol: 8,
    tablecolumncol: 11,
    visible: true,
  },
  {
    name: 'Terbium',
    atomicNumber: 65,
    symbol: 'Tb',
    category: 'Lanthanide',
    atomicWeight: '158.93',
    atomicWeightFull: '158.925354(8) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 0,
    period: 6,
    block: 'f',
    tablerowcol: 8,
    tablecolumncol: 12,
    visible: true,
  },
  {
    name: 'Dysprosium',
    atomicNumber: 66,
    symbol: 'Dy',
    category: 'Lanthanide',
    atomicWeight: '162.5',
    atomicWeightFull: '162.500(1) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 0,
    period: 6,
    block: 'f',
    tablerowcol: 8,
    tablecolumncol: 13,
    visible: true,
  },
  {
    name: 'Holmium',
    atomicNumber: 67,
    symbol: 'Ho',
    category: 'Lanthanide',
    atomicWeight: '164.93',
    atomicWeightFull: '164.930328(7) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 0,
    period: 6,
    block: 'f',
    tablerowcol: 8,
    tablecolumncol: 14,
    visible: true,
  },
  {
    name: 'Erbium',
    atomicNumber: 68,
    symbol: 'Er',
    category: 'Lanthanide',
    atomicWeight: '167.26',
    atomicWeightFull: '167.259(3) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 0,
    period: 6,
    block: 'f',
    tablerowcol: 8,
    tablecolumncol: 15,
    visible: true,
  },
  {
    name: 'Thulium',
    atomicNumber: 69,
    symbol: 'Tm',
    category: 'Lanthanide',
    atomicWeight: '168.93',
    atomicWeightFull: '168.934218(6) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 0,
    period: 6,
    block: 'f',
    tablerowcol: 8,
    tablecolumncol: 16,
    visible: true,
  },
  {
    name: 'Ytterbium',
    atomicNumber: 70,
    symbol: 'Yb',
    category: 'Lanthanide',
    atomicWeight: '173.05',
    atomicWeightFull: '173.045(10) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 0,
    period: 6,
    block: 'f',
    tablerowcol: 8,
    tablecolumncol: 17,
    visible: true,
  },
  {
    name: 'Lutenium',
    atomicNumber: 71,
    symbol: 'Lu',
    category: 'Lanthanide',
    atomicWeight: '174.97',
    atomicWeightFull: '174.9668(1) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 0,
    period: 6,
    block: 'f',
    tablerowcol: 8,
    tablecolumncol: 18,
    visible: true,
  },
  {
    name: 'Hafnium',
    atomicNumber: 72,
    symbol: 'Hf',
    category: 'transition metal',
    atomicWeight: '178.49',
    atomicWeightFull: '178.49(2) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 4,
    period: 6,
    block: 'd',
    tablerowcol: 6,
    tablecolumncol: 4,
    visible: true,
  },
  {
    name: 'Tantalum',
    atomicNumber: 73,
    symbol: 'Ta',
    category: 'transition metal',
    atomicWeight: '180.95',
    atomicWeightFull: '180.94788(2) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 5,
    period: 6,
    block: 'd',
    tablerowcol: 6,
    tablecolumncol: 5,
    visible: true,
  },
  {
    name: 'Tungsten',
    atomicNumber: 74,
    symbol: 'W',
    category: 'transition metal',
    atomicWeight: '183.84',
    atomicWeightFull: '183.84(1) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 6,
    period: 6,
    block: 'd',
    tablerowcol: 6,
    tablecolumncol: 6,
    visible: true,
  },
  {
    name: 'Rhenium',
    atomicNumber: 75,
    symbol: 'Re',
    category: 'transition metal',
    atomicWeight: '186.21',
    atomicWeightFull: '186.207(1) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 7,
    period: 6,
    block: 'd',
    tablerowcol: 6,
    tablecolumncol: 7,
    visible: true,
  },
  {
    name: 'Osmium',
    atomicNumber: 76,
    symbol: 'Os',
    category: 'transition metal',
    atomicWeight: '190.23',
    atomicWeightFull: '190.23(3) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 8,
    period: 6,
    block: 'd',
    tablerowcol: 6,
    tablecolumncol: 8,
    visible: true,
  },
  {
    name: 'Iridium',
    atomicNumber: 77,
    symbol: 'Ir',
    category: 'transition metal',
    atomicWeight: '192.22',
    atomicWeightFull: '192.217(2) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 9,
    period: 6,
    block: 'd',
    tablerowcol: 6,
    tablecolumncol: 9,
    visible: true,
  },
  {
    name: 'Platinum',
    atomicNumber: 78,
    symbol: 'Pt',
    category: 'transition metal',
    atomicWeight: '195.08',
    atomicWeightFull: '195.084(9) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 10,
    period: 6,
    block: 'd',
    tablerowcol: 6,
    tablecolumncol: 10,
    visible: true,
  },
  {
    name: 'Gold',
    atomicNumber: 79,
    symbol: 'Au',
    category: 'transition metal',
    atomicWeight: '196.97',
    atomicWeightFull: '196.966570(4) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 11,
    period: 6,
    block: 'd',
    tablerowcol: 6,
    tablecolumncol: 11,
    visible: true,
  },
  {
    name: 'Mercury',
    atomicNumber: 80,
    symbol: 'Hg',
    category: 'post-transition metal',
    atomicWeight: '200.59',
    atomicWeightFull: '200.592(3) ',
    occurrence: 'Liquid',
    stateOfMatter: 'primordial',
    group: 12,
    period: 6,
    block: 'd',
    tablerowcol: 6,
    tablecolumncol: 12,
    visible: true,
  },
  {
    name: 'Thallium',
    atomicNumber: 81,
    symbol: 'Tl',
    category: 'post-transition metal',
    atomicWeight: '204.38',
    atomicWeightFull: '[204.382, 204.385] ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 13,
    period: 6,
    block: 'p',
    tablerowcol: 6,
    tablecolumncol: 13,
    visible: true,
  },
  {
    name: 'Lead',
    atomicNumber: 82,
    symbol: 'Pb',
    category: 'post-transition metal',
    atomicWeight: '207.2',
    atomicWeightFull: '207.2(1) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 14,
    period: 6,
    block: 'p',
    tablerowcol: 6,
    tablecolumncol: 14,
    visible: true,
  },
  {
    name: 'Bismuth',
    atomicNumber: 83,
    symbol: 'Bi',
    category: 'post-transition metal',
    atomicWeight: '208.98',
    atomicWeightFull: '208.98040(1) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 15,
    period: 6,
    block: 'p',
    tablerowcol: 6,
    tablecolumncol: 15,
    visible: true,
  },
  {
    name: 'Polonium',
    atomicNumber: 84,
    symbol: 'Po',
    category: 'post-transition metal',
    atomicWeight: '[209]',
    atomicWeightFull: '-',
    occurrence: 'solid',
    stateOfMatter: 'from decay',
    group: 16,
    period: 6,
    block: 'p',
    tablerowcol: 6,
    tablecolumncol: 16,
    visible: true,
  },
  {
    name: 'Astatine',
    atomicNumber: 85,
    symbol: 'At',
    category: 'metalloid',
    atomicWeight: '[210]',
    atomicWeightFull: '-',
    occurrence: 'solid',
    stateOfMatter: 'from decay',
    group: 17,
    period: 6,
    block: 'p',
    tablerowcol: 6,
    tablecolumncol: 17,
    visible: true,
  },
  {
    name: 'Radon',
    atomicNumber: 86,
    symbol: 'Rn',
    category: 'noble gas',
    atomicWeight: '[222]',
    atomicWeightFull: '-',
    occurrence: 'gas',
    stateOfMatter: 'from decay',
    group: 18,
    period: 6,
    block: 'p',
    tablerowcol: 6,
    tablecolumncol: 18,
    visible: true,
  },
  {
    name: 'Francium',
    atomicNumber: 87,
    symbol: 'Fr',
    category: 'Alkali metal',
    atomicWeight: '[223]',
    atomicWeightFull: '-',
    occurrence: 'solid',
    stateOfMatter: 'from decay',
    group: 1,
    period: 7,
    block: 's',
    tablerowcol: 7,
    tablecolumncol: 1,
    visible: true,
  },
  {
    name: 'Radium',
    atomicNumber: 88,
    symbol: 'Ra',
    category: 'alkaline earth metal',
    atomicWeight: '[226]',
    atomicWeightFull: '-',
    occurrence: 'solid',
    stateOfMatter: 'from decay',
    group: 2,
    period: 7,
    block: 's',
    tablerowcol: 7,
    tablecolumncol: 2,
    visible: true,
  },
  {
    name: 'Actinium',
    atomicNumber: 89,
    symbol: 'Ac',
    category: 'actinide',
    atomicWeight: '[227]',
    atomicWeightFull: '-',
    occurrence: 'solid',
    stateOfMatter: 'from decay',
    group: 3,
    period: 7,
    block: 'd',
    tablerowcol: 9,
    tablecolumncol: 4,
    visible: true,
  },
  {
    name: 'Thorium',
    atomicNumber: 90,
    symbol: 'Th',
    category: 'actinide',
    atomicWeight: '232.04',
    atomicWeightFull: '232.0377(4) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 0,
    period: 7,
    block: 'f',
    tablerowcol: 9,
    tablecolumncol: 5,
    visible: true,
  },
  {
    name: 'Protactinium',
    atomicNumber: 91,
    symbol: 'Pa',
    category: 'actinide',
    atomicWeight: '231.04',
    atomicWeightFull: '231.03588(1) ',
    occurrence: 'solid',
    stateOfMatter: 'from decay',
    group: 0,
    period: 7,
    block: 'f',
    tablerowcol: 9,
    tablecolumncol: 6,
    visible: true,
  },
  {
    name: 'Uranium',
    atomicNumber: 92,
    symbol: 'U',
    category: 'actinide',
    atomicWeight: '238.03',
    atomicWeightFull: '238.02891(3) ',
    occurrence: 'solid',
    stateOfMatter: 'primordial',
    group: 0,
    period: 7,
    block: 'f',
    tablerowcol: 9,
    tablecolumncol: 7,
    visible: true,
  },
  {
    name: 'Neptunium',
    atomicNumber: 93,
    symbol: 'Np',
    category: 'actinide',
    atomicWeight: '[237]',
    atomicWeightFull: '-',
    occurrence: 'solid',
    stateOfMatter: 'from decay',
    group: 0,
    period: 7,
    block: 'f',
    tablerowcol: 9,
    tablecolumncol: 8,
    visible: true,
  },
  {
    name: 'Plutonium',
    atomicNumber: 94,
    symbol: 'Pu',
    category: 'actinide',
    atomicWeight: '[244]',
    atomicWeightFull: '-',
    occurrence: 'solid',
    stateOfMatter: 'from decay',
    group: 0,
    period: 7,
    block: 'f',
    tablerowcol: 9,
    tablecolumncol: 9,
    visible: true,
  },
  {
    name: 'Americium',
    atomicNumber: 95,
    symbol: 'Am',
    category: 'actinide',
    atomicWeight: '[243]',
    atomicWeightFull: '-',
    occurrence: 'solid',
    stateOfMatter: 'synthetic',
    group: 0,
    period: 7,
    block: 'f',
    tablerowcol: 9,
    tablecolumncol: 10,
    visible: true,
  },
  {
    name: 'Curium',
    atomicNumber: 96,
    symbol: 'Cm',
    category: 'actinide',
    atomicWeight: '[247]',
    atomicWeightFull: '-',
    occurrence: 'solid',
    stateOfMatter: 'synthetic',
    group: 0,
    period: 7,
    block: 'f',
    tablerowcol: 9,
    tablecolumncol: 11,
    visible: true,
  },
  {
    name: 'Berkelium',
    atomicNumber: 97,
    symbol: 'Bk',
    category: 'actinide',
    atomicWeight: '[247]',
    atomicWeightFull: '-',
    occurrence: 'solid',
    stateOfMatter: 'synthetic',
    group: 0,
    period: 7,
    block: 'f',
    tablerowcol: 9,
    tablecolumncol: 12,
    visible: true,
  },
  {
    name: 'Californium',
    atomicNumber: 98,
    symbol: 'Cf',
    category: 'actinide',
    atomicWeight: '[251]',
    atomicWeightFull: '-',
    occurrence: 'solid',
    stateOfMatter: 'synthetic',
    group: 0,
    period: 7,
    block: 'f',
    tablerowcol: 9,
    tablecolumncol: 13,
    visible: true,
  },
  {
    name: 'Einsteinium',
    atomicNumber: 99,
    symbol: 'Es',
    category: 'actinide',
    atomicWeight: '[252]',
    atomicWeightFull: '-',
    occurrence: 'solid',
    stateOfMatter: 'synthetic',
    group: 0,
    period: 7,
    block: 'f',
    tablerowcol: 9,
    tablecolumncol: 14,
    visible: true,
  },
  {
    name: 'Fermium',
    atomicNumber: 100,
    symbol: 'Fm',
    category: 'actinide',
    atomicWeight: '[257]',
    atomicWeightFull: '-',
    occurrence: 'unknown',
    stateOfMatter: 'synthetic',
    group: 0,
    period: 7,
    block: 'f',
    tablerowcol: 9,
    tablecolumncol: 15,
    visible: true,
  },
  {
    name: 'Mendelevium',
    atomicNumber: 101,
    symbol: 'Md',
    category: 'actinide',
    atomicWeight: '[258]',
    atomicWeightFull: '-',
    occurrence: 'unknown',
    stateOfMatter: 'synthetic',
    group: 0,
    period: 7,
    block: 'f',
    tablerowcol: 9,
    tablecolumncol: 16,
    visible: true,
  },
  {
    name: 'Nobelium',
    atomicNumber: 102,
    symbol: 'No',
    category: 'actinide',
    atomicWeight: '[259]',
    atomicWeightFull: '-',
    occurrence: 'unknown',
    stateOfMatter: 'synthetic',
    group: 0,
    period: 7,
    block: 'f',
    tablerowcol: 9,
    tablecolumncol: 17,
    visible: true,
  },
  {
    name: 'Lawrencium',
    atomicNumber: 103,
    symbol: 'Lr',
    category: 'actinide',
    atomicWeight: '[266]',
    atomicWeightFull: '-',
    occurrence: 'unknown',
    stateOfMatter: 'synthetic',
    group: 0,
    period: 7,
    block: 'f',
    tablerowcol: 9,
    tablecolumncol: 18,
    visible: true,
  },
  {
    name: 'Rutherfordium',
    atomicNumber: 104,
    symbol: 'Rf',
    category: 'transition metal',
    atomicWeight: '[267]',
    atomicWeightFull: '-',
    occurrence: 'unknown',
    stateOfMatter: 'synthetic',
    group: 4,
    period: 7,
    block: 'd',
    tablerowcol: 7,
    tablecolumncol: 4,
    visible: true,
  },
  {
    name: 'Dubnium',
    atomicNumber: 105,
    symbol: 'Db',
    category: 'transition metal',
    atomicWeight: '[268]',
    atomicWeightFull: '-',
    occurrence: 'unknown',
    stateOfMatter: 'synthetic',
    group: 5,
    period: 7,
    block: 'd',
    tablerowcol: 7,
    tablecolumncol: 5,
    visible: true,
  },
  {
    name: 'Seaborgium',
    atomicNumber: 106,
    symbol: 'Sg',
    category: 'transition metal',
    atomicWeight: '[269]',
    atomicWeightFull: '-',
    occurrence: 'unknown',
    stateOfMatter: 'synthetic',
    group: 6,
    period: 7,
    block: 'd',
    tablerowcol: 7,
    tablecolumncol: 6,
    visible: true,
  },
  {
    name: 'Bohrium',
    atomicNumber: 107,
    symbol: 'Bh',
    category: 'transition metal',
    atomicWeight: '[270]',
    atomicWeightFull: '-',
    occurrence: 'unknown',
    stateOfMatter: 'synthetic',
    group: 7,
    period: 7,
    block: 'd',
    tablerowcol: 7,
    tablecolumncol: 7,
    visible: true,
  },
  {
    name: 'Hassium',
    atomicNumber: 108,
    symbol: 'Hs',
    category: 'transition metal',
    atomicWeight: '[269]',
    atomicWeightFull: '-',
    occurrence: 'unknown',
    stateOfMatter: 'synthetic',
    group: 8,
    period: 7,
    block: 'd',
    tablerowcol: 7,
    tablecolumncol: 8,
    visible: true,
  },
  {
    name: 'Meitnerium',
    atomicNumber: 109,
    symbol: 'Mt',
    category: 'unknown',
    atomicWeight: '[278]',
    atomicWeightFull: '-',
    occurrence: 'unknown',
    stateOfMatter: 'synthetic',
    group: 9,
    period: 7,
    block: 'd',
    tablerowcol: 7,
    tablecolumncol: 9,
    visible: true,
  },
  {
    name: 'Darmstadtium',
    atomicNumber: 110,
    symbol: 'Ds',
    category: 'unknown',
    atomicWeight: '[281]',
    atomicWeightFull: '-',
    occurrence: 'unknown',
    stateOfMatter: 'synthetic',
    group: 10,
    period: 7,
    block: 'd',
    tablerowcol: 7,
    tablecolumncol: 10,
    visible: true,
  },
  {
    name: 'Roentgenium',
    atomicNumber: 111,
    symbol: 'Rg',
    category: 'unknown',
    atomicWeight: '[282]',
    atomicWeightFull: '-',
    occurrence: 'unknown',
    stateOfMatter: 'synthetic',
    group: 11,
    period: 7,
    block: 'd',
    tablerowcol: 7,
    tablecolumncol: 11,
    visible: true,
  },
  {
    name: 'Copernicum',
    atomicNumber: 112,
    symbol: 'Cn',
    category: 'post-transition metal',
    atomicWeight: '[285]',
    atomicWeightFull: '-',
    occurrence: 'unknown',
    stateOfMatter: 'synthetic',
    group: 12,
    period: 7,
    block: 'd',
    tablerowcol: 7,
    tablecolumncol: 12,
    visible: true,
  },
  {
    name: 'Nihonium',
    atomicNumber: 113,
    symbol: 'Nh',
    category: 'unknown',
    atomicWeight: '[286]',
    atomicWeightFull: '-',
    occurrence: 'unknown',
    stateOfMatter: 'synthetic',
    group: 13,
    period: 7,
    block: 'p',
    tablerowcol: 7,
    tablecolumncol: 13,
    visible: true,
  },
  {
    name: 'Flerovium',
    atomicNumber: 114,
    symbol: 'Fl',
    category: 'unknown',
    atomicWeight: '[289]',
    atomicWeightFull: '-',
    occurrence: 'unknown',
    stateOfMatter: 'synthetic',
    group: 14,
    period: 7,
    block: 'p',
    tablerowcol: 7,
    tablecolumncol: 14,
    visible: true,
  },
  {
    name: 'Moscovium',
    atomicNumber: 115,
    symbol: 'Mc',
    category: 'unknown',
    atomicWeight: '[290]',
    atomicWeightFull: '-',
    occurrence: 'unknown',
    stateOfMatter: 'synthetic',
    group: 15,
    period: 7,
    block: 'p',
    tablerowcol: 7,
    tablecolumncol: 15,
    visible: true,
  },
  {
    name: 'Livermorium',
    atomicNumber: 116,
    symbol: 'Lv',
    category: 'unknown',
    atomicWeight: '[293]',
    atomicWeightFull: '-',
    occurrence: 'unknown',
    stateOfMatter: 'synthetic',
    group: 16,
    period: 7,
    block: 'p',
    tablerowcol: 7,
    tablecolumncol: 16,
    visible: true,
  },
  {
    name: 'Tennessine',
    atomicNumber: 117,
    symbol: 'Ts',
    category: 'unknown',
    atomicWeight: '[294]',
    atomicWeightFull: '-',
    occurrence: 'unknown',
    stateOfMatter: 'synthetic',
    group: 17,
    period: 7,
    block: 'p',
    tablerowcol: 7,
    tablecolumncol: 17,
    visible: true,
  },
  {
    name: 'Oganesson',
    atomicNumber: 118,
    symbol: 'Og',
    category: 'unknown',
    atomicWeight: '[294]',
    atomicWeightFull: '-',
    occurrence: 'unknown',
    stateOfMatter: 'synthetic',
    group: 18,
    period: 7,
    block: 'p',
    tablerowcol: 7,
    tablecolumncol: 18,
    visible: true,
  },
];

module.exports = periodicTableData;
